services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: mah
      POSTGRES_PASSWORD: mah
      POSTGRES_DB: mah
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://mah:mah@db:5432/mah?schema=public
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres-data:
